# Generated by Django 4.1.4 on 2022-12-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_remove_diary_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
