# Generated by Django 4.1.4 on 2022-12-29 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_alter_account_password_alter_account_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='admin',
        ),
    ]
